### ISSUE TITLE
service.py is empty

### ISSUE THREAD

**Issue by turing4ever** [talkpython/mastering-pycharm-course#1]
Hi Mike, 

service.py is empty. I guess it's an accident?
mastering-pycharm-course/your-turn/4-refactoring/smelly_podcast/service.py

**Comment by mikeckennedy** [comment]
Hi @turing4ever,

That is intentional. Your job on this step is to move things out of program into that file. 

https://github.com/talkpython/mastering-pycharm-course/tree/master/your-turn/4-refactoring#large-module-smell

I just created the file so you had it already in place to work with.
