### ISSUE TITLE
Is PyCharm professional required for the Data Science "Your Turn" Lab?

### ISSUE THREAD

**Issue by andrew6850** [talkpython/mastering-pycharm-course#10]
Is PyCharm Professional Edition required for the data science "Your Turn: lab? If so, you might want to list that at the top of the "Your Turn" lab.  Thanks!

The course may have mentioned this prerequisite, but I think PyCharm Professional Edition is required for the Data Science Lab.  I spent some time trying to figure out how to turn on Data Science Mode, and couldn't find it in the new project wizard.

**Then I stumbled upon this:**
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000682290-PyCharm-EAP-where-s-the-scientific-mode-

**and this:**
https://www.jetbrains.com/pycharm/features/editions_comparison_matrix.html

I could be wrong, but it looks like you need Professional Edition for this lab.

Thanks,
Andrew

**Comment by mikeckennedy** [comment]
Hi @andrew6850 Yes it is apparently! Sorry about that. I added indicators to the 4 sections that require PyCharm Pro. Thanks for the tip. Here's the commit:

https://github.com/talkpython/mastering-pycharm-course/commit/6c5b414ed3f10d5129a46f4746abbc2444479ca3
