### ISSUE TITLE
bad_wizard readme

### ISSUE THREAD

**Issue by blzfrost** [talkpython/mastering-pycharm-course#11]
Not sure if it's just me, but after reformatting and removing imports the hero.attack ended up on line 58 of instead of the line 57 stated on lines 44 and 48 of the bad_wizard readme. ;)
I'm using pycharm pro 2018.1.3 and running  Linux Mint 18.3

**Comment by mikeckennedy** [comment]
Hi @blzfrost Thanks for the heads up. @sambozek was kind enough to jump in and fix this via a PR. Appreciate it from both of you.
