### ISSUE TITLE
Part 7 -  Quick info re Cython extensions on Linux

### ISSUE THREAD

**Issue by swedishmike** [talkpython/mastering-pycharm-course#18]
Just a quick comment re the Cython extensions under Linux in Part 7.

I'm currently running 2018.2 and at least from that version you no longer need to manually cut-paste the instructions for how to install the Cython extensions for debugging.

There's the normal 'install something' link being displayed and you just click that and PyCharm sorts it all for you. 

Nothing major, just a minor change in behaviour that may or may not be useful to add if you update the content at some stage in the future.

Cheers, Mike

**Comment by mikeckennedy** [comment]
Hi Mike. 

Thanks for the feedback. Yes, they converted that to something you click and it just happens was really smart. I don't think it's worth updating the video but having it here as a Github issue might help someone. 

Best,
Michael
