### ISSUE TITLE
"Add method wake_up to Wizard class" is not working

### ISSUE THREAD

**Issue by leongrin** [talkpython/mastering-pycharm-course#20]
![wake_up method](https://user-images.githubusercontent.com/41086608/48156748-c4466480-e2ac-11e8-95a6-3d8999048eb9.jpg)

The instruction below is not working, as you can see on the attached image.

"Notice that wake_up should have some warning about it not existing. Put your cursor on wake_up, press alt-enter, and choose "Add method wake_up to Wizard class"."

**Comment by mikeckennedy** [comment]
Hi

The problem is you need to indent that hero.wake_up() line. It's not part of the game_loop() method where hero exists at the moment.
