### ISSUE TITLE
Consider adding PyCharm's Jupyter Notebooks support video

### ISSUE THREAD

**Issue by mikeckennedy** [talkpython/mastering-pycharm-course#24]
Now that PyCharm has more direct support for Jupyter, consider adding a short section on this directly.

**Comment by edgarinvillegas** [comment]
I think this is a must. Many people (like me) purchased PyCharm Professional to develop jupyter notebooks, and it's not very intuitive.
Please add this section.

**Comment by mikeckennedy** [comment]
Thanks for the extra info @edgarinvillegas We're working on a rewrite/rerecord of that chapter so I'll keep this in mind.
