### ISSUE TITLE
bad_wizard missing Wizard.attack() function

### ISSUE THREAD

**Issue by jgoldfed** [talkpython/mastering-pycharm-course#25]
Class Wizard in 2-the editor folder is missing an the .attack() function. This is causing an unresolved reference in the program.py file (note, this was probably a miss, but could be added to instructions on how to resolve)

**Comment by jgoldfed** [comment]
Actually, on my machine, we are calling the wrong import function: your-turn/2-the-editor/bad_wizard/actors.py does contain the _attack_ function, program.py (same directory) is callilng demos/wizard/actors.py which does not contain the _attack_ function. This is causing the problem.

**Comment by mikeckennedy** [comment]
Ah, glad you figured it out. Probably you have both sections loaded in PyCharm and both have "mark directory as source root" set. At least, that's what trips me up when I hit this type of error.
