### ISSUE TITLE
With current version (2020 May) views.py <> default.py

### ISSUE THREAD

**Issue by hkokko** [talkpython/mastering-pycharm-course#32]
In the instructions views.py is mentioned. With the current version of tooling and framework it seems default.py is the place this should be added. at least that works.

**Comment by mikeckennedy** [comment]
Hi @hkokko Thanks. This is for creating the Pyramid web app right?

**Comment by hkokko** [comment]
Yes. 6-web-applications your turn

	
Hannu Kokko
hannukokko.me

**Comment by mikeckennedy** [comment]
Thanks. That got out of sync because PyCharm switched to Cookiecutter under the covers (as they should have!) but that uses a different layout.
