### ISSUE TITLE
The course is called "Effective Python", the repo still refers to the previous course "Mastering Python"

### ISSUE THREAD

**Issue by ReddyKilowatt** [talkpython/mastering-pycharm-course#56]
It's a minor issue. But since I have both courses in my bundle, and that "Mastering" has been superseded by "Effective", it makes one wonder if the the sources were updated but not appropriately linked in the "Effective PyCharm" page

**Comment by mikeckennedy** [comment]
Hi @ReddyKilowatt Yes, Effective PyCharm has superseded the original course. Thanks for the catch!

**Comment by mikeckennedy** [comment]
BTW, just for anyone who comes across this, I kept the repo name/url the same as the original because so many people were using and linking to it. Seems too disruptive to justify it.
