### ISSUE TITLE
Instructions say 'Folder' when 'File' may be more accurate

### ISSUE THREAD

**Issue by BrownLogic** [talkpython/mastering-pycharm-course#8]
This line:  "Create a **folder** next to views.py called fake_data.py. Copy this method into that file:" (*emphasis added*) would probably me more accurate if it said:

"Create a **file** next to views.py"

**Comment by BrownLogic** [comment]
Closed while trying to get pull request working from Pycharm.  I'm sure it was PEBKAC

**Comment by mikeckennedy** [comment]
Yes, indeed. Thank you for the PR!
